services:
    postgresdb:
        container_name: postgresdb
        image: postgres:13.3
        restart: always
        volumes:
            - './postgres_data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=sa123456
        ports:
            - 5432:5432
        networks:
            - postgres
    jupyter:
        build: './jupyter'
        depends_on:
            postgresdb: 
                condition: service_started
        container_name: jupyter
        volumes:
            - './jupyter/notebooks:/notebooks'
        ports:
            - 8888:8888
        networks:
            - postgres
    dash:
        build: './dash'
        depends_on:
            postgresdb: 
                condition: service_started
        container_name: dash
        volumes:
            - './dash/src:/src'
        ports:
            - 8050:8050
        networks:
            - postgres
networks:
    postgres:
        driver: bridge