services:
    postgresdb:
        container_name: postgresdb
        image: postgres:13.3
        restart: always
        volumes:
            - './postgres_data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=sa123456
        ports:
            - 5432:5432
    jupyter:
        build: './jupyter'
        depends_on:
            - postgresdb
        container_name: jupyter
        volumes:
            - './jupyter/notebooks:/notebooks'
        ports:
            - 8888:8888
    dash:
        build: './dash'
        depends_on:
            - postgresdb
        container_name: dash
        volumes:
            - './dash/src:/src'
        ports:
            - 8050:8050
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"
        depends_on:
            - postgresdb
