services:
    postgresdb:
        container_name: postgresdb
        image: postgres:13.3
        restart: always
        volumes:
            - './postgres_data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=sa123456
        ports:
            - 5432:5432
    jupyter:
        container_name: jupyter
        build: './jupyter'
        volumes:
            - './jupyter:/var/lib/jupyter'
        ports:
            - 8888:8888
    dash:
        container_name: dash
        build: './dash'
        volumes:
            - './dash:/var/lib/dash'
        ports:
            - 8050:8050
